<?php

/**
 *  后台继承类
 * @file   Admin.php   
 */

namespace app\admin\controller;

use app\admin\model\Admin as A;
use app\admin\model\AdminGroup;
use app\admin\model\AdminGroupAccess;

class Admin extends Common {

    protected $_AdminGroupAccess;
    protected $_Admin;
    protected $_AdminGroup;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_AdminGroupAccess = new AdminGroupAccess();
        $this->_Admin = new A();
        $this->_AdminGroup = new AdminGroup();
    }

    public function index() {
        $where = array();
        if ($group_id = input('group_id')){
            $where['t2.GroupId'] = $group_id;
        }
        $lists = $this->_Admin
                ->alias('t1')
                ->field('t1.*')
                ->where($where)
                ->join('admin_group_access t2', 't1.Id=t2.UId', 'left')
                ->group('t1.Id')
                ->order('t1.Id desc')
                ->select();
        foreach ($lists as $k => $v) {
            //取出组名
            $lists[$k]['Groups'] = '';
            $groups = $this->_AdminGroupAccess->getUserGroups($v['Id']);
            if ($groups) {
                $tmp = $this->_AdminGroup->field('Name')->where('Id', 'in', $groups)->select();

                foreach ($tmp as $vv) {
                    $lists[$k]['Groups'] .= $vv['Name'] . ',';
                }
                $lists[$k]['Groups'] = trim($lists[$k]['Groups'], ',');
            }
        }
        $this->assign('lists', $lists);
        return $this->fetch();
    }

    /*
     * 查看
     */

    public function info() {
        $id = input('id');
        $url = $id ? 'edit' : 'add';
        if ($id) {
            //当前用户信息
            $info = $this->_Admin->getInfo($id);
            $info['userGroups'] = $this->_Admin->getUserGroups($id);
            $this->assign('info', $info);
        }

        //所有组信息
        $groups = $this->_AdminGroup->getGroups();
        $this->assign('groups', $groups);
        $this->assign('url', url($url));
        return $this->fetch();
    }

    public function add() {
        $data = input();
        $count = $this->_Admin->where('NickName', $data['NickName'])->count();

        if ($count) {
            $this->error('用户名已存在');
        }

        if ($data['password'] != $data['rpassword']) {
            $this->error('两次密码不一致');
        }

        $data['L1Pwd'] = md5($data['password']);
        $res = $this->_Admin->allowField(true)->save($data);

        if ($res) {
            if (isset($data['groups'])) {
                $uid = model('Admin')->id;
                foreach ($data['groups'] as $v) {
                    $this->_AdminGroupAccess->insert(['UId' => $uid, 'GroupId' => $v]);
                }
            }
            $this->success('操作成功', url('index'));
        } else {
            $this->error('操作失败');
        }
    }

    public function edit() {
        $data = input();
        $this->_AdminGroupAccess->where(['UId' => $data['Id']])->delete();

        if (isset($data['groups'])) {
            foreach ($data['groups'] as $v) {
                $this->_AdminGroupAccess->insert(['UId' => $data['Id'], 'GroupId' => $v]);
            }
        }


        if (!$data['password']) {
            unset($data['password']);
        } else {
            if ($data['password'] != $data['rpassword']) {
                $this->error('两次密码不一致!');
            }
            $data['L1Pwd'] = md5($data['password']);
        }

        // p($data);exit();
        $res = $this->_Admin->editInfo(2, $data['Id'], $data);

        if ($res) {
            $this->success('操作成功', url('index'));
        } else {
            $this->error('操作失败');
        }
    }

    public function del() {
        $id = input('id');
        $res = $this->_Admin->where(['Id' => $id])->delete();
        if ($res) {
            $this->_AdminGroupAccess->where(['UId' => $id])->delete();
            $this->success('操作成功', url('index'));
        } else {
            $this->error('操作失败');
        }
    }

    public function public_edit_info() {
        $data = input();
        if (isset($data['dosubmit'])) {
            if (!$data['password']) {
                unset($data['password']);
            } else {
                if ($data['password'] != $data['rpassword']) {
                    $this->error('两次密码不一致!');
                }
                $data['password'] = md5($data['password']);
            }

            $res = $this->_Admin->editInfo(2, $this->user_id, $data);

            if ($res) {
                $this->success('修改成功');
            } else {
                $this->error('修改失败');
            }
        } else {
            $info = $this->_Admin->where('id', $this->user_id)->find();
            $this->assign('info', $info);
            return $this->fetch();
        }
    }

}
